// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_application_1/test/golden_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_application_1/service/login/login_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeJWT_0 extends _i1.Fake implements _i2.JWT {}

/// A class which mocks [LoginService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginService extends _i1.Mock implements _i2.LoginService {
  MockLoginService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url =>
      (super.noSuchMethod(Invocation.getter(#url), returnValue: '') as String);
  @override
  _i3.Future<_i2.JWT> login(Object? credential) => (super.noSuchMethod(
      Invocation.method(#login, [credential]),
      returnValue: Future<_i2.JWT>.value(_FakeJWT_0())) as _i3.Future<_i2.JWT>);
}
